version: "3.8"
services:
  web:    
    image: samiahmedshaik77/ejbca-ce
    restart: always
    environment:
      DATABASE_JDBC_URL: jdbc:mysql://db:3306/ejbca-database?characterEncoding=UTF-8
      DATABASE_USER: ejbca
      DATABASE_PASSWORD: pa$$w0rd
      ORG_NAME: PAM
      CA_NAME: RootCA
      SMTP_DESTINATION: mail
    ports:
      - "8443:8443"
      - "8080:8080"
    depends_on:
      - db
      - mail
    hostname: pki.pam.com
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pa$$w0rd
      MYSQL_DATABASE: ejbca-database
      MYSQL_USER: ejbca
      MYSQL_PASSWORD: pa$$w0rd  
    volumes:
      - dbdatavolume:/var/lib/mysql
    hostname: pki-db.pam.com
  mail:
    image: samiahmedshaik77/poste.io
    restart: always
    environment:
      HTTPS_PORT: 9443
      HTTP_PORT: 9080
    ports:
      - "9443:9443"
      - "9080:9080"
    volumes:
      - maildatavolume:/data 
    hostname: pki-mail.pam.com    
volumes:
  dbdatavolume:
  maildatavolume:
